# Generated by Django 6.1 on 2026-08-08 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admininfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='jktransadmin@gmail.com', max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(default='JKTransAdmin2026', max_length=100)),
            ],
        ),
    ]
