# Generated by Django 5.2.9 on 2026-08-05 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('annee', models.DateField(verbose_name='date')),
                ('couleur', models.CharField(max_length=50)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/vehicules/')),
                ('plaque', models.CharField(max_length=20, unique=True)),
                ('nombre_siege', models.PositiveIntegerField(default=4)),
                ('Chauffeur', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='gestion_vehicules.chauffeur')),
            ],
        ),
    ]
